# Generated by Django 5.2.1 on 2025-05-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
